import { Animal } from "../types/animal-types";

/**
 * Mock data for animal adoption platform
 * Used for development and testing purposes
 * Contains diverse examples of animals available for adoption
 */
export const mockAnimals: Animal[] = [
  {
    id: 1,
    nome: "Max",
    especie: "cachorro",
    raca: "Golden Retriever",
    idade: 3,
    sexo: "macho",
    porte: "grande",
    descricao: "Max é um cão muito carinhoso e brincalhão. Adora crianças e outros animais. Foi encontrado abandonado mas está em perfeitas condições de saúde. Procura uma família que possa oferecer muito amor e carinho.",
    status: "disponivel",
    imagemUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "São Paulo, SP",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 2,
    nome: "Luna",
    especie: "gato",
    raca: "Siamês",
    idade: 2,
    sexo: "fêmea",
    porte: "pequeno",
    descricao: "Luna é uma gatinha muito elegante e independente. É carinhosa com pessoas conhecidas e adora brincar com bolinhas. Está castrada e com todas as vacinas em dia.",
    status: "disponivel",
    imagemUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "Rio de Janeiro, RJ",
    createdAt: "2024-01-20T14:30:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: 3,
    nome: "Bobby",
    especie: "cachorro",
    raca: "Vira-lata",
    idade: 5,
    sexo: "macho",
    porte: "médio",
    descricao: "Bobby é um cachorro muito dócil e obediente. Ideal para famílias com crianças. Já é castrado e está com todas as vacinas atualizadas. Procura um lar definitivo.",
    status: "disponivel",
    imagemUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "Belo Horizonte, MG",
    createdAt: "2024-01-10T08:15:00Z",
    updatedAt: "2024-01-10T08:15:00Z",
  },
  {
    id: 4,
    nome: "Mimi",
    especie: "gato",
    raca: "Persa",
    idade: 1,
    sexo: "fêmea",
    porte: "pequeno",
    descricao: "Mimi é uma gatinha jovem e muito brincalhona. Adora carinho e ronronar no colo. É muito sociável e se dá bem com outros gatos.",
    status: "disponivel",
    imagemUrl: "https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "Porto Alegre, RS",
    createdAt: "2024-01-25T16:45:00Z",
    updatedAt: "2024-01-25T16:45:00Z",
  },
  {
    id: 5,
    nome: "Thor",
    especie: "cachorro",
    raca: "Pastor Alemão",
    idade: 4,
    sexo: "macho",
    porte: "grande",
    descricao: "Thor é um cão de guarda muito leal e protetor. Precisa de uma família experiente com cães grandes. É muito inteligente e obediente quando bem treinado.",
    status: "disponivel",
    imagemUrl: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "Brasília, DF",
    createdAt: "2024-01-05T12:20:00Z",
    updatedAt: "2024-01-05T12:20:00Z",
  },
  {
    id: 6,
    nome: "Bella",
    especie: "cachorro",
    raca: "Labrador",
    idade: 6,
    sexo: "fêmea",
    porte: "grande",
    descricao: "Bella é uma cadela muito carinhosa e calma. Ideal para famílias com crianças pequenas. Já está castrada e com todas as vacinas em dia.",
    status: "adotado",
    imagemUrl: "https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400&h=300&fit=crop",
    abrigoId: 1,
    localizacao: "Salvador, BA",
    createdAt: "2024-01-01T09:00:00Z",
    updatedAt: "2024-01-28T15:30:00Z",
  }
];
